### PR TITLE
Add Python3 compatibility, use distutils and fix compiler issue

### PR DESCRIPTION
**Pull request by mdshw5**
These changes add backward-compatible Python3 support (which was just changing print from a statement to a function) and also fixes issue #1.

### CODE REVIEW

**Comment by brentp** [comment]
thanks!

**Comment by brentp** [comment]
the tests are failing due to bytes/str issues in python3.

**Comment by mdshw5** [comment]
Oh yes, I forgot that I’m adding bytes to the filter. I’ll make a small modification that uses explicit encoding for PY3.

On Apr 30, 2014, at 4:04 PM, Brent Pedersen - Bioinformatics notifications@github.com wrote:

> the tests are failing due to bytes/str issues in python3.
> 
> —
> Reply to this email directly or view it on GitHub.

Matt Shirley

**Comment by brentp** [comment]
so this does fix #1?

**Comment by mdshw5** [comment]
Yes, I believe it does because I am using it under MacOS 10.9 with Python3.4 and 2.7.

On May 2, 2014, at 12:58 PM, Brent Pedersen - Bioinformatics notifications@github.com wrote:

> so this does fix #1?
> 
> —
> Reply to this email directly or view it on GitHub.

Matt Shirley

**Pull request merged**
